server {
    listen 80;
    listen [::]:80;
    server_name dostuffandhavefun.com www.dostuffandhavefun.com;

    root /var/www/dostuffandhavefun.com;
    index index.html;

    access_log /var/log/nginx/dostuffandhavefun.com.access.log;
    error_log /var/log/nginx/dostuffandhavefun.com.error.log;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
